/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var checkType = require('kurento-client').checkType;

/**
 * Checker for {@link facesegmentator/complexTypes.Point}
 *
 * @memberof module:facesegmentator/complexTypes
 *
 * @param {external:String} key
 * @param {module:facesegmentator/complexTypes.Point} value
 */
function checkPoint(key, value)
{
  checkType('int', key+'.x', value.x, true);
  checkType('int', key+'.y', value.y, true);
};


/**
 * Point coordinates.
 *
 * @memberof module:facesegmentator/complexTypes
 *
 * @typedef facesegmentator/complexTypes.Point
 *
 * @type {Object}
 * @property {external:Integer} x
 *  Position in pixels of X coordinate of the point
 * @property {external:Integer} y
 *  Position in pixels of Y coordinate of the point
 */


module.exports = checkPoint;
