/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * Event generated when a face is detected
 *
 * @event module:facesegmentator#EyesPosition
 *
 * @type {module:facesegmentator#event:Media}
 *
 * @property {module:facesegmentator/complexTypes.Point} leftEye
 *  central coordinate of the left eye
 * @property {module:facesegmentator/complexTypes.Point} rightEye
 *  central coordinate of the left eye
 */

/**
 * Event generated when a face is detected
 *
 * @event module:facesegmentator#FacePosition
 *
 * @type {module:facesegmentator#event:Media}
 *
 * @property {module:facesegmentator/complexTypes.Point} leftPoint
 *  left coordinate of the region of the face
 * @property {module:facesegmentator/complexTypes.Point} topPoint
 *  top coordinate of the region of the face
 * @property {module:facesegmentator/complexTypes.Point} rightPoint
 *  right coordinate of the region of the face
 * @property {module:facesegmentator/complexTypes.Point} bottomPoint
 *  bottom coordinate of the region of the face
 */

/**
 * Event generated when a face is detected
 *
 * @event module:facesegmentator#MouthPosition
 *
 * @type {module:facesegmentator#event:Media}
 *
 * @property {module:facesegmentator/complexTypes.Point} leftPoint
 *  left coordinate of the region of the mouth
 * @property {module:facesegmentator/complexTypes.Point} centralPoint
 *  central coordinate of the region of the mouth
 * @property {module:facesegmentator/complexTypes.Point} rightPoint
 *  right coordinate of the region of the mouth
 */

/**
 * Event generated when a face is detected
 *
 * @event module:facesegmentator#NoisePosition
 *
 * @type {module:facesegmentator#event:Media}
 *
 * @property {module:facesegmentator/complexTypes.Point} centralPoint
 *  central coordinate of the noise
 */
