/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */


/**
 * Event generated when a face is detected
 *
 * @event module:facesegmentator#EyesPosition
 *
 * @type {module:facesegmentator#event:Media}
 *
 * @property {module:facesegmentator/complexTypes.Point} leftEye
 *  central coordinate of the left eye
 * @property {module:facesegmentator/complexTypes.Point} rightEye
 *  central coordinate of the left eye
 */

/**
 * Event generated when a face is detected
 *
 * @event module:facesegmentator#FacePosition
 *
 * @type {module:facesegmentator#event:Media}
 *
 * @property {module:facesegmentator/complexTypes.Point} leftPoint
 *  left coordinate of the region of the face
 * @property {module:facesegmentator/complexTypes.Point} topPoint
 *  top coordinate of the region of the face
 * @property {module:facesegmentator/complexTypes.Point} rightPoint
 *  right coordinate of the region of the face
 * @property {module:facesegmentator/complexTypes.Point} bottomPoint
 *  bottom coordinate of the region of the face
 */

/**
 * Event generated when a face is detected
 *
 * @event module:facesegmentator#MouthPosition
 *
 * @type {module:facesegmentator#event:Media}
 *
 * @property {module:facesegmentator/complexTypes.Point} leftPoint
 *  left coordinate of the region of the mouth
 * @property {module:facesegmentator/complexTypes.Point} centralPoint
 *  central coordinate of the region of the mouth
 * @property {module:facesegmentator/complexTypes.Point} rightPoint
 *  right coordinate of the region of the mouth
 */

/**
 * Event generated when a face is detected
 *
 * @event module:facesegmentator#NoisePosition
 *
 * @type {module:facesegmentator#event:Media}
 *
 * @property {module:facesegmentator/complexTypes.Point} centralPoint
 *  central coordinate of the noise
 */
